name: deploy-firefox
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
 
jobs:
  firefox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: npm install
        uses: actions/setup-node@v4
 
      - name: Install dependencies
        run: npm install
 
      - name: Install web-ext
        run: npm i web-ext
 
      - name: lint
        run: npm run lint:check
     
      - name: run
        run: npm run build:firefox

      - name: Sign with web-ext
        run: |
          npx web-ext sign \
          --api-key ${{ secrets.USER }} \
          --api-secret ${{ secrets.MOZILLA }} \
          --channel unlisted \
          --source-dir ./* \
          --artifacts-dir ./signed 